export interface IS_TRX_PAY_PAYMENT {
    TSM_TRNSACTIONID: string;
    PMT_PAYMENTROWID: string;
    PMT_TRANSACTIONTYPE: string;
    CLY_YEAR: number | null;
    CLP_PERIOD: number | null;
    PMT_INSTTYPE: string;
    PMT_INSTNAME: string;
    PMT_INSTNUMBER: string;
    PMT_INSTDATE: Date | null;
    PMT_INSTTIME: number;
    PMT_INSTACCODE: string;
    PMT_INSTBANKCODE: number;
    PMT_INSTBANKBRCODE: number;
    PMT_SLIPNO: string;
    PMT_REALIZEDATE: Date | null;
    PMT_REALIZETIME: number;
    PMT_CANCELDATE: Date | null;
    PMT_CANCELTIME: number;
    PMT_PAYMENTSTATE: string;
    PMT_STATUS: string;
    PMT_EXECUTEDBY: string;
    PMT_EXECUTEDON: string | null;
    PMT_EXECUTIONSTATUS: string;
    PMT_COMMENT: string;
    PMT_PAYMENTCURRSYMBOL: string;
    PMT_CONVDATE: Date | null;
    PMT_CONVRATE: number;
    PMT_REVISIONNO: number;
    PMT_ISAUTORECONCILED: number;
    PMT_CREATEDBY: string;
    PMT_CREATEDON: Date;
    PMT_MODIFIEDON: string | null;
    PMT_MODIFIEDBY: string;
    PMT_DIGITALSIGNATURE: string;
    TSTAMP: string;
    CAC_ACCOUNTID: string | null;
    PMT_PAYMENTAMOUNT: number;
    PMT_PRDCURRSYMBOL: string;
    PMT_CONERTEDAMOUNT: number;
    PMT_EXECUTIONSENTTO: string;
    PMT_VERIFIEDBY: string;
    PMT_VERIFIEDON: string | null;
    PMT_ISVERIFIED: number;
    PMT_ISIMPORTED: number;
    PRD_PRODUCTCODE: string;
    BNK_ID: number | null;
    BBR_ID: number | null;
    FAC_ACCOUNTNO: string;
    PMT_INSTACTITLE: string;
    PMT_PRCNUMBER: string;
    TSD_REQTRXID: string;
    TRF_REQPLANFUNDID: string;
    PMT_INSTOTHERBANK: number | null;
}