export interface IS_TRX_TRX_MASTER {
    TSM_TRNSACTIONID: string;
    TSM_USERTRXCODE: string;
    TSM_YEARTRXCOUNT: number;
    TSM_PERIODTRXCOUNT: number;
    TSM_TRXDATE: string | null;
    TSM_TRXTIME: number | null;
    TSM_PROCESSTIME: number | null;
    TSM_PROCESSDATE: string | null;
    TSM_ISREVERSAL: number;
    TSM_ISAMCTRX: number;
    TSM_FORMNO: string;
    TSM_COMMENTS: string;
    TSM_ISONLINE: number;
    TSM_ISARCHIVABLE: number;
    TSM_LINKEDTRXCODE: string;
    TSM_ISSYSTEMTRX: number;
    TSM_PROCESSID: string;
    TSM_VOUCHERID: string;
    TSM_STATUS: string;
    TSM_CREATEDBY: string;
    TSM_CREATEDON: string | null;
    TSM_LASTMODIFIEDBY: string;
    TSM_LASTMODIFIEDON: string | null;
    TSM_ISVERIFIED: number;
    TSM_VERIFIEDBY: string;
    TSM_VERIFIEDON: string | null;
    TSM_DIGITALCERTIFICATE: string;
    TSTAMP: string;
    TSM_ISCANCELLED: number;
    DST_ID: string;
    DSB_ID: string;
    TSM_TRXTYPE: string;
    TSM_TRXNAME: string;
    CLP_PERIOD: number | null;
    CLY_YEAR: number | null;
    TSM_ISPROCESSED: number;
    ACC_SYSTEMCODE: string;
    CUS_CODE: number | null;
    TSM_ACCOUNTCODE: number;
    TSM_TRXCOUNT: number;
    TSM_ISREVERSED: number;
    TSM_ISVISIBLEINCUSTREPORTS: number;
    TSM_AGENTCODE: string;
    TSM_ACCOUNTTYPE: string;
    TSM_ISSTATEMENTDISPATCHED: number;
    TSM_DISPATCHMETHOD: string;
    TSM_DISPATCHON: string | null;
    TSM_DISPATCHREFID: string;
    TSM_DISPATCHBY: string;
    TSM_REGISTRARCODE: string;
    TSM_ISIPO: number;
    TSM_ISVPS: number;
    TSM_DISPATCHRECIEVEDBY: string;
    TSM_TOACCOUNTCODE: number;
    TSM_ISIMPORTED: number;
    TSM_CONTRIBUTIONTYPE: string;
    TSM_VERSION: number;
    TSM_REVERSETRANSACTIONID: string;
    TSM_ISNAVANNOUNCED: number | null;
    TSM_NAVANNOUNCEDDATE: string | null;
    TSM_NAVANNOUNCEDTIME: number | null;
    TSM_BACKENDLOADPERCENT: number | null;
    TSM_FACILITATORREBATE?: number | null;
    TSM_PFCONTRIBUTION: number | null;
    TSM_AGENTCODE2: string;
    ADC_TYPEID: number | null;
    TSM_ISADC: number | null;
    TSM_PURPOSE: string;
    
}